### ISSUE TITLE
ZIP_Read: corrupt zip file: invalid entry size

### ISSUE THREAD

**Issue by stivendarsi** [Speedy11CZ/mcrpx#2]
It extracts a few folders and images and then stops.

**Comment by Speedy11CZ** [comment]
Would it be possible to upload your resourcepack somewhere?

**Comment by Splatcrafter** [comment]
same issue for me, i tried it with the cytooxien.de (German Server) but there are the same message after a few files.

**Comment by Splatcrafter** [comment]
I found the issue. You must run it with Java 17. Java 8 has many bugs with it.

**Comment by Speedy11CZ** [comment]
> I found the issue. You must run it with Java 17. Java 8 has many bugs with it.

The whole tool is developed on Java 17, so it is possible that the tool behaves unpredictably on older versions.

**Comment by Speedy11CZ** [comment]
MCRPX now uses Java 17 as minimum version to run.
