### ISSUE TITLE
Improve resource pack decryption against "directory" obfuscation.

### ISSUE THREAD

**Issue by NadCatKim** [Speedy11CZ/mcrpx#5]
## Description

MCRPX cannot handle resource packs produced by PackSquash (version after 2023-09-24 commit) with enabled obfuscation on `disregard` level.

## Cause

On 2023-09-24, [PackSquash improved resource pack encryption](https://github.com/ComunidadAylas/PackSquash/commit/ea933d50675366d36d9e23af55e0c4e38d232388) by obfuscating *certain* files and treating them as directories (see attached screenshots).

## Steps to recreate

1. Download the **latest** PackSquash program artifact from **GitHub Actions** (not from "Releases" page!);
2. Download or/and extract any valid Minecraft resource pack in desired directory;
3. Create a new options file with `.toml` extension, then copy these settings:

```toml
pack_directory = "HERE_GOES_YOUR_RESOURCE_PACK_DIRECTORY"
size_increasing_zip_obfuscation = true
zip_spec_conformance_level = "disregard"
```

Replace `HERE_GOES_YOUR_RESOURCE_PACK_DIRECTORY` with your extracted resource pack directory and save the options file.

4. Open a terminal, go to the PackSquash program directory, run `packsquash.exe "PATH_TO_OPTIONS_FILE.TOML"`. Replace `PATH_TO_OPTIONS_FILE.TOML` with your options file name;
5. Run MCPRX and try to extract encrypted resource pack.

## Intended behavior

MCPRX exports encrypted resource pack.

## Observed behavior

MCPRX throws an error: "Invalid input file! Must be resource pack or Minecraft jar file".

## Screenshots
![RRP_Source](https://github.com/Speedy11CZ/mcrpx/assets/93866416/de8ecac7-8357-44ae-a5b8-ab402b67f9d1)
![RRP_Encrypted](https://github.com/Speedy11CZ/mcrpx/assets/93866416/8d711275-5256-4c0f-a996-c10bc1f9e8c5)
![MCPRX_Error](https://github.com/Speedy11CZ/mcrpx/assets/93866416/a0fe9a39-2e4f-4562-aab7-7fbd976b998d)

**Comment by Speedy11CZ** [comment]
It should be fixed, thanks for reporting it.
