### ISSUE TITLE
Well

### ISSUE THREAD

**Issue by Kanddaa** [Speedy11CZ/mcrpx#6]
I don't see the point of this. You are contributing in helping people to steal/modify other people's work. Your repo says it itself: "It can bypass corrupted resource packs, used by servers to **protect** their resource packs.", so why making this tool? You made it even though you knew it was bad, and it is really disrespectful towards the work of people.

I'm myself using the corruption method to protect my resource packs, and knowing that people can just use this tool to steal my work is really discouraging.

**Comment by lolouthefox** [comment]
Hi,
I believe it is against any software like ZIP software to intentionally corrupt it or the format for such purposes, if you believe this software shouldn't exist then so should the curruption "protection" method. Also, such projects do not care what you do with it. Techinically nothing illegal or against any ToS is done here.
Additionaly this tool can be useful in many situations such as if you "secured" a resourcepack and need it back. Or if you want to learn from some people's work.
If you believe this software has been misused and you know who used it wrongly I do not see anything stopping you to poursue legal actions against this person for wrongly using your work.

At least this is my point of view, and i do understand it is frustrating that people are using this tool to steal your work.

Have a nice day!

**Comment by GravelCZ** [comment]
If you are sending any data(like a resource pack) to a target user there is no way to prevent anyone from reading it. If this tool didn't exist others would use something like RenderDoc to rip the assets directly from gpu memory. If you are angry about someone stealing the work complain about them, not the tool. It's like you made a hammer, someone used it to break someones window and then blame you for it. It does not make sense.

**Comment by Kanddaa** [comment]
> If you are sending any data(like a resource pack) to a target user there is no way to prevent anyone from reading it. If this tool didn't exist others would use something like RenderDoc to rip the assets directly from gpu memory. If you are angry about someone stealing the work complain about them, not the tool. It's like you made a hammer, someone used it to break someones window and then blame you for it. It does not make sense.

Hello there,
I understand your point of view, however if we take your example, the hammer hasn't been made for harm purposes, or has it? This tool has been made particularly and specifically for breaking the protection of resource packs as said in the repo, nothing else, that's why i'm blaming it. For now resource packs work in that zip format, they don't have their own minecraft-compatible format, so we need to do it that way unfortunately. So if we use that protection method, it is for a good reason which is to protect our work against potential copyright stealing or bad usage.
That's only my opinion, and as a content creator i find it bad to have our only hope of work protection and safety being so easily breakable by anyone.

**Comment by natereprogle** [comment]
I think you skipped the part in the readme where it says "Despite the fact that this tool allows extracting corrupted resource packs, please note that the content may be subject to copyright. Use this tool at your own risk.". 

https://github.com/Speedy11CZ/mcrpx#warning

As long as you aren't distributing any Mojang-created resources, your packs are protected by your automatically-issued copyright. Anyone unzipping them to steal the content is doing so illegally, and you can (theoretically) sue them for damages. DMCA is one hell of a law.

**Comment by Kanddaa** [comment]
> I think you skipped the part in the readme where it says "Despite the fact that this tool allows extracting corrupted resource packs, please note that the content may be subject to copyright. Use this tool at your own risk.".
> 
> https://github.com/Speedy11CZ/mcrpx#warning
> 
> As long as you aren't distributing any Mojang-created resources, your packs are protected by your automatically-issued copyright. Anyone unzipping them to steal the content is doing so illegally, and you can (theoretically) sue them for damages. DMCA is one hell of a law.

As far as i know, you need to pay to get yourself such a guard like DMCA, and i'm not able to afford anything and i shouldn't be supposed to do that just to protect my own work. I did not skip the readme part, and i'll give you an example. Let's that i give you a gun and i tell you that you can be legally punished for using it without permission or at all, use it at your own risk. Is it fair that i don't risk anything just because i warned you about using this gun and only you can be legally punished even for just having it? That's the same case here, You can't just give people a tool then say that it shouldn't be used for the purpose of breaking work protection while it's almost the only purpose this tool was made for.

**Comment by lolouthefox** [comment]
Lmao: USA
Jokes aside, you do not need to pay to claim content. But attacking open source tools is kinda shitty when nobody actually used to steal content as far as I know. I personally use it for debugging since my resource packs are dynamic on my server. If you really think this is the only reason texture packs get stolen then idk what to say... Just find another game to mod or make a mod for encrypted texture packs... But the nature of Minecraft texture packs is it is easy to make and look inside to learn from others.
If you get content stolen don't go after the tool but after the people who stole your content... Again, it's like Photoshop, you can do degrading images but the tool isn't banned because you can do that!

**Comment by Speedy11CZ** [comment]
This software in no way "breaks" the security of resource packs, it just opens and extracts them in the same way as Minecraft. So while it can open corrupted resource packs, it is up to the user whether they use it with good or bad intent. There is a disclaimer about this in the README.md. Another advantage is, for example, the ability to extract a resource pack directly from the game's .jar file.
